### ISSUE TITLE
Skills Book and Mastery don't save

### ISSUE THREAD

**Issue by Daniel4rt** [Darkin47/SagaRevised#6] opened 2015-04-23 22:48 UTC
So just that, when you learn a Skill Book and relogin into the game it's dissapear and need to buy again, so this happen, the first skill "Short Sword Skill" don't be auto-learned by playrers :cactus:

**Comment by loentar** [comment] 2017-09-10 21:55
Actually server loads only first skill due to #10.

**Comment by JulienGrv** [comment] 2017-09-17 11:49
Duplicate of issue #10

**Closed as completed by JulienGrv** 2017-09-17 11:49 UTC
Labels: bug, major
